spring.sql.init.platform=postgresql
app.timezone=Europe/Moscow
server.port=9090
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.username=dbuser
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.datasource.initialization-mode=always
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java